In [1]:
from configs.base_config import ForecastingModuleConfig
from entities.model_class import ModelClass
from model_wrappers.model_factory import ModelFactory
from modules.data_fetcher_module import DataFetcherModule
from utils.config_util import read_config_file
from utils.fetch_india_district_data import get_india_district_data_from_url, get_population_value
import pandas as pd
import json

In [2]:
config = json.loads('{ "region_name": "bengaluru", "region_type": "district", "run_day": "3/22/20", "forecast_start_date": "4/1/20", "forecast_end_date": "4/20/20", "model_class": "SEIR", "model_parameters": { "infectious_period": 9.5412, "incubation_period": 6, "EbyCRatio": 0.69906, "IbyCRatio": 0.78, "r0": 2.4091, "LatentEbyCRatio": { "3/22/20": 0.69906, "4/1/20": 0.5781344247805147 }, "LatentIbyCRatio": { "3/22/20": 0.78, "4/1/20": 0.7781344247805147 } }, "forecast_variables": [ "confirmed", "recovered", "deceased" ], "output_filepath": "seir_forecast2.csv" }')

In [3]:
forecasting_module_config = ForecastingModuleConfig.parse_obj(config)

In [6]:
forecasting_module_config.model_parameters.update({"MAPE": 7.2})

In [7]:
forecasting_module_config.model_parameters

{'infectious_period': 9.5412,
 'incubation_period': 6,
 'EbyCRatio': 0.69906,
 'IbyCRatio': 0.78,
 'r0': 2.4091,
 'LatentEbyCRatio': {'3/22/20': 0.69906, '4/1/20': 0.5781344247805147},
 'LatentIbyCRatio': {'3/22/20': 0.78, '4/1/20': 0.7781344247805148},
 'MAPE': 7.2}

In [8]:
model = ModelFactory.get_model("SEIR", forecasting_module_config.model_parameters)

In [9]:
# def predict(self, region_type, region_name, region_metadata, region_observations, run_day, forecast_start_date,
#                 forecast_end_date, model_parameters):

(region_type, region_name, run_day, forecast_start_date, forecast_end_date) = (forecasting_module_config.region_type, forecasting_module_config.region_name, forecasting_module_config.run_day, forecasting_module_config.forecast_start_date,forecasting_module_config.forecast_end_date)

In [10]:

region_observations = DataFetcherModule.get_observations_for_region(region_type, region_name)
region_metadata = DataFetcherModule.get_regional_metadata(region_type, region_name)

In [62]:

predictions_df = model.predict(region_metadata, region_observations, run_day, forecast_start_date,
                                     forecast_end_date)
dates = predictions_df['date']

t = 29.90

In [63]:
preddf = predictions_df.set_index('date')

In [64]:
preddf

,actual_confirmed,exposed,active,recovered,deceased,confirmed,hospitalized,actual_recovered
date,,,,,,,,
4/1/20,46,51.700876,37.626119,25.398182,0.677980,63.702282,9.782791,13
4/2/20,46,58.614932,42.603235,29.489441,0.787192,72.879868,11.076841,14
4/3/20,46,66.428022,48.251662,34.120998,0.910827,83.283488,12.545432,14
4/4/20,50,75.263634,54.660005,39.365829,1.050833,95.076667,14.211601,14
4/5/20,50,85.267005,61.925634,45.307411,1.209438,108.442483,16.100665,15
4/6/20,51,96.605113,70.154691,52.039718,1.389151,123.583559,18.240220,19
4/7/20,54,109.465715,79.473650,59.670876,1.592857,140.737384,20.663149,20
4/8/20,55,124.034575,90.029548,68.315397,1.823614,160.168559,23.407682,20
4/9/20,60,140.523452,101.985180,78.102156,2.084862,182.172199,26.516147,20
4/10/20,62,159.187046,115.530538,89.184170,2.380686,207.095395,30.037940,20
4/11/20,64,180.322994,130.882810,101.738595,2.715815,235.337219,34.029531,20
4/12/20,67,204.271876,148.286380,115.966725,3.095621,267.348726,38.554459,22
4/13/20,68,231.417209,168.012832,132.093996,3.526123,303.632951,43.683336,26
4/14/20,71,262.185452,190.360946,150.369983,4.013983,344.744912,49.493846,26
4/15/20,73,297.048404,215.660980,171.070704,4.566569,391.298253,56.071855,26
4/16/20,78,336.546573,244.320952,194.522596,5.192595,444.036143,63.523448,26
4/17/20,88,381.280389,276.785878,221.085447,5.901665,503.772990,71.964328,26
4/18/20,91,431.946536,313.563143,251.173662,6.704841,571.441646,81.526417,26
4/19/20,91,489.345829,355.233542,285.262787,7.614818,648.111148,92.360721,26
4/20/20,91,554.383208,402.451288,323.889506,8.645921,734.986716,104.637335,26

In [65]:
preddf = preddf.transpose().reset_index()
preddf = preddf.rename(columns = {"index": "prediction_type", })

In [66]:
preddf

date,prediction_type,4/1/20,4/2/20,4/3/20,4/4/20,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,...,4/11/20,4/12/20,4/13/20,4/14/20,4/15/20,4/16/20,4/17/20,4/18/20,4/19/20,4/20/20
0,actual_confirmed,46,46,46,50,50,51,54,55,60,...,64,67,68,71,73,78,88,91,91,91
1,exposed,51.7009,58.6149,66.428,75.2636,85.267,96.6051,109.466,124.035,140.523,...,180.323,204.272,231.417,262.185,297.048,336.547,381.28,431.947,489.346,554.383
2,active,37.6261,42.6032,48.2517,54.66,61.9256,70.1547,79.4737,90.0295,101.985,...,130.883,148.286,168.013,190.361,215.661,244.321,276.786,313.563,355.234,402.451
3,recovered,25.3982,29.4894,34.121,39.3658,45.3074,52.0397,59.6709,68.3154,78.1022,...,101.739,115.967,132.094,150.37,171.071,194.523,221.085,251.174,285.263,323.89
4,deceased,0.67798,0.787192,0.910827,1.05083,1.20944,1.38915,1.59286,1.82361,2.08486,...,2.71581,3.09562,3.52612,4.01398,4.56657,5.19259,5.90166,6.70484,7.61482,8.64592
5,confirmed,63.7023,72.8799,83.2835,95.0767,108.442,123.584,140.737,160.169,182.172,...,235.337,267.349,303.633,344.745,391.298,444.036,503.773,571.442,648.111,734.987
6,hospitalized,9.78279,11.0768,12.5454,14.2116,16.1007,18.2402,20.6631,23.4077,26.5161,...,34.0295,38.5545,43.6833,49.4938,56.0719,63.5234,71.9643,81.5264,92.3607,104.637
7,actual_recovered,13,14,14,14,15,19,20,20,20,...,20,22,26,26,26,26,26,26,26,26

In [67]:
activeSeries = preddf[preddf['prediction_type'] == 'active'][dates]

In [68]:
activeSeries

date,4/1/20,4/2/20,4/3/20,4/4/20,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,4/10/20,4/11/20,4/12/20,4/13/20,4/14/20,4/15/20,4/16/20,4/17/20,4/18/20,4/19/20,4/20/20
2,37.6261,42.6032,48.2517,54.66,61.9256,70.1547,79.4737,90.0295,101.985,115.531,130.883,148.286,168.013,190.361,215.661,244.321,276.786,313.563,355.234,402.451

In [69]:
amp = activeSeries.multiply((0.07))

In [70]:
amp['prediction_type'] = 'active_min'

In [71]:
amp

date,4/1/20,4/2/20,4/3/20,4/4/20,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,4/10/20,...,4/12/20,4/13/20,4/14/20,4/15/20,4/16/20,4/17/20,4/18/20,4/19/20,4/20/20,prediction_type
2,2.63383,2.98223,3.37762,3.8262,4.33479,4.91083,5.56316,6.30207,7.13896,8.08714,...,10.38,11.7609,13.3253,15.0963,17.1025,19.375,21.9494,24.8663,28.1716,active_min

In [72]:
preddf = preddf.append(amp)

In [73]:
preddf

,prediction_type,4/1/20,4/2/20,4/3/20,4/4/20,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,...,4/11/20,4/12/20,4/13/20,4/14/20,4/15/20,4/16/20,4/17/20,4/18/20,4/19/20,4/20/20
0,actual_confirmed,46,46,46,50,50,51,54,55,60,...,64,67,68,71,73,78,88,91,91,91
1,exposed,51.7009,58.6149,66.428,75.2636,85.267,96.6051,109.466,124.035,140.523,...,180.323,204.272,231.417,262.185,297.048,336.547,381.28,431.947,489.346,554.383
2,active,37.6261,42.6032,48.2517,54.66,61.9256,70.1547,79.4737,90.0295,101.985,...,130.883,148.286,168.013,190.361,215.661,244.321,276.786,313.563,355.234,402.451
3,recovered,25.3982,29.4894,34.121,39.3658,45.3074,52.0397,59.6709,68.3154,78.1022,...,101.739,115.967,132.094,150.37,171.071,194.523,221.085,251.174,285.263,323.89
4,deceased,0.67798,0.787192,0.910827,1.05083,1.20944,1.38915,1.59286,1.82361,2.08486,...,2.71581,3.09562,3.52612,4.01398,4.56657,5.19259,5.90166,6.70484,7.61482,8.64592
5,confirmed,63.7023,72.8799,83.2835,95.0767,108.442,123.584,140.737,160.169,182.172,...,235.337,267.349,303.633,344.745,391.298,444.036,503.773,571.442,648.111,734.987
6,hospitalized,9.78279,11.0768,12.5454,14.2116,16.1007,18.2402,20.6631,23.4077,26.5161,...,34.0295,38.5545,43.6833,49.4938,56.0719,63.5234,71.9643,81.5264,92.3607,104.637
7,actual_recovered,13,14,14,14,15,19,20,20,20,...,20,22,26,26,26,26,26,26,26,26
2,active_min,2.63383,2.98223,3.37762,3.8262,4.33479,4.91083,5.56316,6.30207,7.13896,...,9.1618,10.38,11.7609,13.3253,15.0963,17.1025,19.375,21.9494,24.8663,28.1716

In [13]:
model.model_parameters

{'infectious_period': 9.5412,
 'incubation_period': 6,
 'EbyCRatio': 0.69906,
 'IbyCRatio': 0.78,
 'r0': 2.4091,
 'LatentEbyCRatio': {'3/22/20': 0.69906, '4/1/20': 0.5781344247805147},
 'LatentIbyCRatio': {'3/22/20': 0.78, '4/1/20': 0.7781344247805148},
 'MAPE': 7.2}

In [109]:

predictions_df = model.predict(region_metadata, region_observations, run_day, forecast_start_date,
                                     forecast_end_date)
dates = predictions_df['date']
preddf = predictions_df.set_index('date')
preddf = preddf.transpose().reset_index()
preddf = preddf.rename(columns = {"index": "prediction_type", })
error = float(forecasting_module_config.model_parameters['MAPE'])/100
for col in [ForecastVariable.active.name, ForecastVariable.hospitalized.name, ForecastVariable.icu.name,
            ForecastVariable.recovered.name, ForecastVariable.deceased.name, ForecastVariable.confirmed.name]:    
    series = preddf[preddf['prediction_type'] == col][dates]
    newSeries = series.multiply((1-error))
    newSeries['prediction_type'] = col+'_min'
    preddf = preddf.append(newSeries, ignore_index = True)
    newSeries = series.multiply((1+error))
    newSeries['prediction_type'] = col+'_max'
    preddf = preddf.append(newSeries, ignore_index = True)
    preddf.rename(columns = {col: col+'_mean'})
preddf.insert(0, 'Province/State', region_name)
preddf.insert(1, 'Country/Region', 'India')
preddf.insert(2, 'Lat', 20)
preddf.insert(3, 'Long', 70)

t = 29.90

In [108]:
from entities.forecast_variables import ForecastVariable
ForecastVariable.recovered.name

'recovered'

In [104]:
pred = preddf.copy()

In [105]:
pred['Provinve/State'] = region_name
pred['Country/Region'] = "India"
pred['Lat'] = 20
pred['Long'] = 70

In [106]:
j = preddf.to_json()

In [110]:
preddf

,Province/State,Country/Region,Lat,Long,prediction_type,4/1/20,4/2/20,4/3/20,4/4/20,4/5/20,...,4/11/20,4/12/20,4/13/20,4/14/20,4/15/20,4/16/20,4/17/20,4/18/20,4/19/20,4/20/20
0,bengaluru,India,20,70,actual_confirmed,46,46,46,50,50,...,64,67,68,71,73,78,88,91,91,91
1,bengaluru,India,20,70,exposed,51.7009,58.6149,66.428,75.2636,85.267,...,180.323,204.272,231.417,262.185,297.048,336.547,381.28,431.947,489.346,554.383
2,bengaluru,India,20,70,active,37.6261,42.6032,48.2517,54.66,61.9256,...,130.883,148.286,168.013,190.361,215.661,244.321,276.786,313.563,355.234,402.451
3,bengaluru,India,20,70,recovered,25.3982,29.4894,34.121,39.3658,45.3074,...,101.739,115.967,132.094,150.37,171.071,194.523,221.085,251.174,285.263,323.89
4,bengaluru,India,20,70,deceased,0.67798,0.787192,0.910827,1.05083,1.20944,...,2.71581,3.09562,3.52612,4.01398,4.56657,5.19259,5.90166,6.70484,7.61482,8.64592
5,bengaluru,India,20,70,confirmed,63.7023,72.8799,83.2835,95.0767,108.442,...,235.337,267.349,303.633,344.745,391.298,444.036,503.773,571.442,648.111,734.987
6,bengaluru,India,20,70,hospitalized,9.78279,11.0768,12.5454,14.2116,16.1007,...,34.0295,38.5545,43.6833,49.4938,56.0719,63.5234,71.9643,81.5264,92.3607,104.637
7,bengaluru,India,20,70,actual_recovered,13,14,14,14,15,...,20,22,26,26,26,26,26,26,26,26
8,bengaluru,India,20,70,active_min,34.917,39.5358,44.7775,50.7245,57.467,...,121.459,137.61,155.916,176.655,200.133,226.73,256.857,290.987,329.657,373.475
9,bengaluru,India,20,70,active_max,40.3352,45.6707,51.7258,58.5955,66.3843,...,140.306,158.963,180.11,204.067,231.189,261.912,296.714,336.14,380.81,431.428
10,bengaluru,India,20,70,hospitalized_min,9.07843,10.2793,11.6422,13.1884,14.9414,...,31.5794,35.7785,40.5381,45.9303,52.0347,58.9498,66.7829,75.6565,85.7107,97.1034
11,bengaluru,India,20,70,hospitalized_max,10.4872,11.8744,13.4487,15.2348,17.2599,...,36.4797,41.3304,46.8285,53.0574,60.109,68.0971,77.1458,87.3963,99.0107,112.171
12,bengaluru,India,20,70,recovered_min,23.5695,27.3662,31.6643,36.5315,42.0453,...,94.4134,107.617,122.583,139.543,158.754,180.517,205.167,233.089,264.724,300.569
13,bengaluru,India,20,70,recovered_max,27.2269,31.6127,36.5777,42.2002,48.5695,...,109.064,124.316,141.605,161.197,183.388,208.528,237.004,269.258,305.802,347.21
14,bengaluru,India,20,70,deceased_min,0.629166,0.730515,0.845248,0.975173,1.12236,...,2.52028,2.87274,3.27224,3.72498,4.23778,4.81873,5.47675,6.22209,7.06655,8.02341
15,bengaluru,India,20,70,deceased_max,0.726795,0.84387,0.976407,1.12649,1.29652,...,2.91135,3.31851,3.78,4.30299,4.89536,5.56646,6.32658,7.18759,8.16308,9.26843
16,bengaluru,India,20,70,confirmed_min,59.1157,67.6325,77.2871,88.2311,100.635,...,218.393,248.1,281.771,319.923,363.125,412.066,467.501,530.298,601.447,682.068
17,bengaluru,India,20,70,confirmed_max,68.2888,78.1272,89.2799,101.922,116.25,...,252.281,286.598,325.495,369.567,419.472,476.007,540.045,612.585,694.775,787.906

In [100]:
j

'{"Province\\/State":{"0":"bengaluru","1":"bengaluru","2":"bengaluru","3":"bengaluru","4":"bengaluru","5":"bengaluru","6":"bengaluru","7":"bengaluru","8":"bengaluru","9":"bengaluru","10":"bengaluru","11":"bengaluru","12":"bengaluru","13":"bengaluru","14":"bengaluru","15":"bengaluru"},"Country\\/Region":{"0":"India","1":"India","2":"India","3":"India","4":"India","5":"India","6":"India","7":"India","8":"India","9":"India","10":"India","11":"India","12":"India","13":"India","14":"India","15":"India"},"Lat":{"0":20,"1":20,"2":20,"3":20,"4":20,"5":20,"6":20,"7":20,"8":20,"9":20,"10":20,"11":20,"12":20,"13":20,"14":20,"15":20},"Long":{"0":70,"1":70,"2":70,"3":70,"4":70,"5":70,"6":70,"7":70,"8":70,"9":70,"10":70,"11":70,"12":70,"13":70,"14":70,"15":70},"prediction_type":{"0":"actual_confirmed","1":"exposed","2":"active","3":"recovered","4":"deceased","5":"confirmed","6":"hospitalized","7":"actual_recovered","8":"active_min","9":"active_max","10":"recovered_min","11":"recovered_max","12":"deceased_min","13":"deceased_max","14":"confirmed_min","15":"confirmed_max"},"4\\/1\\/20":{"0":46.0,"1":51.700875803,"2":37.6261193911,"3":25.3981824379,"4":0.6779802293,"5":63.7022820584,"6":9.7827910417,"7":13.0,"8":34.917038795,"9":40.3351999873,"10":23.5695133024,"11":27.2268515734,"12":0.6291656528,"13":0.7267948059,"14":59.1157177502,"15":68.2888463666},"4\\/2\\/20":{"0":46.0,"1":58.6149322678,"2":42.6032350283,"3":29.4894408582,"4":0.7871924664,"5":72.8798683529,"6":11.0768411073,"7":14.0,"8":39.5358021062,"9":45.6706679503,"10":27.3662011164,"11":31.6126805999,"12":0.7305146089,"13":0.843870324,"14":67.6325178315,"15":78.1272188743},"4\\/3\\/20":{"0":46.0,"1":66.4280216743,"2":48.2516624358,"3":34.1209976988,"4":0.910827454,"5":83.2834875886,"6":12.5454322333,"7":14.0,"8":44.7775427404,"9":51.7257821312,"10":31.6642858645,"11":36.5777095331,"12":0.8452478773,"13":0.9764070307,"14":77.2870764822,"15":89.279898695},"4\\/4\\/20":{"0":50.0,"1":75.263634125,"2":54.6600048743,"3":39.3658290554,"4":1.0508332191,"5":95.0766671488,"6":14.2116012673,"7":14.0,"8":50.7244845234,"9":58.5955252253,"10":36.5314893634,"11":42.2001687474,"12":0.9751732274,"13":1.1264932109,"14":88.2311471141,"15":101.9221871836},"4\\/5\\/20":{"0":50.0,"1":85.2670045107,"2":61.925634183,"3":45.3074106546,"4":1.2094380668,"5":108.4424829044,"6":16.1006648876,"7":15.0,"8":57.4669885219,"9":66.3842798442,"10":42.0452770874,"11":48.5695442217,"12":1.1223585259,"13":1.2965176076,"14":100.6346241353,"15":116.2503416735},"4\\/6\\/20":{"0":51.0,"1":96.6051125098,"2":70.1546907803,"3":52.039717854,"4":1.3891505793,"5":123.5835592136,"6":18.2402196029,"7":19.0,"8":65.1035530441,"9":75.2058285165,"10":48.2928581685,"11":55.7865775395,"12":1.2891317376,"13":1.489169421,"14":114.6855429502,"15":132.481575477},"4\\/7\\/20":{"0":54.0,"1":109.4657150678,"2":79.4736500333,"3":59.6708764397,"4":1.5928570713,"5":140.7373835443,"6":20.6631490087,"7":20.0,"8":73.7515472309,"9":85.1957528357,"10":55.374573336,"11":63.9671795433,"12":1.4781713622,"13":1.7075427804,"14":130.6042919291,"15":150.8704751595},"4\\/8\\/20":{"0":55.0,"1":124.0345746284,"2":90.0295477006,"3":68.3153966982,"4":1.8236142856,"5":160.1685586844,"6":23.4076824022,"7":20.0,"8":83.5474202662,"9":96.5116751351,"10":63.3966881359,"11":73.2341052605,"12":1.692314057,"13":1.9549145141,"14":148.6364224591,"15":171.7006949097},"4\\/9\\/20":{"0":60.0,"1":140.523452042,"2":101.9851803399,"3":78.1021561898,"4":2.0848624856,"5":182.1721990153,"6":26.5161468884,"7":20.0,"8":94.6422473554,"9":109.3281133243,"10":72.4788009441,"11":83.7255114355,"12":1.9347523866,"13":2.2349725845,"14":169.0558006862,"15":195.2885973443},"4\\/10\\/20":{"0":62.0,"1":159.1870458113,"2":115.530538399,"3":89.1841704146,"4":2.3806862739,"5":207.0953950875,"6":30.0379399837,"7":20.0,"8":107.2123396343,"9":123.8487371637,"10":82.7629101447,"11":95.6054306844,"12":2.2092768622,"13":2.5520956856,"14":192.1845266412,"15":222.0062635338},"4\\/11\\/20":{"0":64.0,"1":180.3229943593,"2":130.8828098078,"3":101.7385948302,"4":2.7158146464,"5":235.3372192844,"6":34.02953055,"7":20.0,"8":121.4592475016,"9":140.3063721139,"10":94.4134160024,"11":109.063773658,"12":2.5202759919,"13":2.9113533009,"14":218.3929394959,"15":252.2814990729},"4\\/12\\/20":{"0":67.0,"1":204.2718760285,"2":148.2863799778,"3":115.9667248522,"4":3.0956209919,"5":267.348725822,"6":38.5544587942,"7":22.0,"8":137.6097606194,"9":158.9629993362,"10":107.6171206629,"11":124.3163290416,"12":2.8727362805,"13":3.3185057034,"14":248.0996175628,"15":286.5978340812},"4\\/13\\/20":{"0":68.0,"1":231.4172090815,"2":168.0128318027,"3":132.0939958537,"4":3.5261230926,"5":303.632950749,"6":43.6833362687,"7":26.0,"8":155.915907913,"9":180.1097556925,"10":122.5832281522,"11":141.6047635552,"12":3.2722422299,"13":3.7800039553,"14":281.7713782951,"15":325.494523203},"4\\/14\\/20":{"0":71.0,"1":262.1854517007,"2":190.3609456579,"3":150.3699831655,"4":4.0139831235,"5":344.7449119469,"6":49.4938458711,"7":26.0,"8":176.6549575705,"9":204.0669337453,"10":139.5433443776,"11":161.1966219534,"12":3.7249763386,"13":4.3029899084,"14":319.9232782867,"15":369.5665456071},"4\\/15\\/20":{"0":73.0,"1":297.0484042942,"2":215.6609802254,"3":171.070704081,"4":4.5665691028,"5":391.2982534091,"6":56.0718548586,"7":26.0,"8":200.1333896491,"9":231.1885708016,"10":158.7536133872,"11":183.3877947748,"12":4.2377761274,"13":4.8953620782,"14":363.1247791637,"15":419.4717276546},"4\\/16\\/20":{"0":78.0,"1":336.5465728487,"2":244.3209520446,"3":194.5225963484,"4":5.1925949744,"5":444.0361433674,"6":63.5234475316,"7":26.0,"8":226.7298434974,"9":261.9120605918,"10":180.5169694113,"11":208.5282232855,"12":4.8187281362,"13":5.5664618125,"14":412.065541045,"15":476.0067456899},"4\\/17\\/20":{"0":88.0,"1":381.2803885402,"2":276.7858783105,"3":221.0854469966,"4":5.9016649096,"5":503.7729902167,"6":71.9643283607,"7":26.0,"8":256.8572950722,"9":296.7144615489,"10":205.1672948128,"11":237.0035991803,"12":5.4767450361,"13":6.326584783,"14":467.5013349211,"15":540.0446455123},"4\\/18\\/20":{"0":91.0,"1":431.9465362405,"2":313.5631427305,"3":251.1736622923,"4":6.7048410879,"5":571.4416461107,"6":81.5264171099,"7":26.0,"8":290.9865964539,"9":336.1396890071,"10":233.0891586073,"11":269.2581659774,"12":6.2220925296,"13":7.1875896462,"14":530.2978475907,"15":612.5854446306},"4\\/19\\/20":{"0":91.0,"1":489.3458289993,"2":355.2335424755,"3":285.2627873949,"4":7.6148177333,"5":648.1111476037,"6":92.3607210436,"7":26.0,"8":329.6567274173,"9":380.8103575338,"10":264.7238667024,"11":305.8017080873,"12":7.0665508565,"13":8.1630846101,"14":601.4471449763,"15":694.7751502312},"4\\/20\\/20":{"0":91.0,"1":554.3832080442,"2":402.4512881806,"3":323.889506356,"4":8.6459211142,"5":734.9867156508,"6":104.6373349269,"7":26.0,"8":373.4747954316,"9":431.4277809296,"10":300.5694618984,"11":347.2095508136,"12":8.023414794,"13":9.2684274345,"14":682.0676721239,"15":787.9057591777}}'