In [18]:
import pandas as pd
import numpy as np

In [56]:
##Data Source (https://www.kaggle.com/sudalairajkumar/covid19-in-italy)

In [4]:
filepath= "../data/covid19-in-italy/covid19_italy_region.csv"

In [5]:
italy_df = pd.read_csv(filepath, sep=",")

In [15]:
italy_df.head()

,SNo,Date,Country,RegionCode,RegionName,Latitude,Longitude,HospitalizedPatients,IntensiveCarePatients,TotalHospitalizedPatients,HomeConfinement,CurrentPositiveCases,NewPositiveCases,Recovered,Deaths,TotalPositiveCases,TestsPerformed,date_formatted
0,0,2020-02-24T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,0,0,0,0,0,5,02/24/2020
1,1,2020-02-24T18:00:00,ITA,17,Basilicata,40.639471,15.805148,0,0,0,0,0,0,0,0,0,0,02/24/2020
2,2,2020-02-24T18:00:00,ITA,4,P.A. Bolzano,46.499335,11.356624,0,0,0,0,0,0,0,0,0,1,02/24/2020
3,3,2020-02-24T18:00:00,ITA,18,Calabria,38.905976,16.594402,0,0,0,0,0,0,0,0,0,1,02/24/2020
4,4,2020-02-24T18:00:00,ITA,15,Campania,40.839566,14.250850,0,0,0,0,0,0,0,0,0,10,02/24/2020

In [13]:
##format date
italy_df["date_formatted"] = pd.to_datetime(italy_df["Date"], infer_datetime_format=True).apply(lambda x: x.strftime("%m/%d/%Y"))

In [17]:
columns = ["RegionName", "Latitude", "Longitude", "TotalPositiveCases", "date_formatted"]
italy_df = italy_df[columns]

In [44]:
italy_df["Country/Region"]="Italy"

In [50]:
datewise_df = pd.pivot_table(italy_df, index=['RegionName','Country/Region', 'Latitude', 'Longitude'],
                    columns=['date_formatted'], values=["TotalPositiveCases"], aggfunc=np.sum).fillna(0)

In [51]:
datewise_df.columns = [element[1] for element in datewise_df.columns]

In [52]:
datewise_df.reset_index(inplace=True)

In [53]:
datewise_df.rename(columns={"Latitude": "Lat", "Longitude": "Long", "RegionName": "Province/State"}, inplace=True)

In [54]:
datewise_df

,Province/State,Country/Region,Lat,Long,02/24/2020,02/25/2020,02/26/2020,02/27/2020,02/28/2020,02/29/2020,...,03/31/2020,04/01/2020,04/02/2020,04/03/2020,04/04/2020,04/05/2020,04/06/2020,04/07/2020,04/08/2020,04/09/2020
0,Abruzzo,Italy,42.351222,13.398438,0,0,0,1,1,2,...,1401,1436,1497,1563,1628,1703,1721,1799,1859,1931
1,Basilicata,Italy,40.639471,15.805148,0,0,0,0,0,0,...,226,237,246,261,264,278,287,291,297,303
2,Calabria,Italy,38.905976,16.594402,0,0,0,0,1,1,...,659,669,691,733,741,795,817,833,859,874
3,Campania,Italy,40.839566,14.250850,0,0,0,3,4,13,...,2092,2231,2456,2677,2828,2960,3058,3148,3268,3344
4,Emilia-Romagna,Italy,44.494367,11.341721,18,26,47,97,145,217,...,14074,14787,15333,15932,16540,17089,17556,17825,18234,18677
5,Friuli Venezia Giulia,Italy,45.649435,13.768136,0,0,0,0,0,0,...,1593,1685,1799,1879,1986,2048,2103,2153,2218,2299
6,Lazio,Italy,41.892770,12.483667,3,3,3,3,3,6,...,3095,3264,3433,3600,3757,3880,4031,4149,4266,4429
7,Liguria,Italy,44.411493,8.932699,0,1,11,19,19,42,...,3416,3660,3782,3965,4203,4449,4549,4757,4906,5020
8,Lombardia,Italy,45.466794,9.190347,172,240,258,403,531,615,...,43208,44773,46065,47520,49118,50455,51534,52325,53414,54802
9,Marche,Italy,43.616760,13.518875,0,0,1,3,6,11,...,3825,3962,4098,4230,4341,4464,4614,4710,4859,4955
10,Molise,Italy,41.557748,14.659161,0,0,0,0,0,0,...,144,160,165,176,206,224,224,224,226,234
11,P.A. Bolzano,Italy,46.499335,11.356624,0,1,1,1,1,1,...,1371,1418,1479,1559,1592,1644,1722,1811,1835,1903
12,P.A. Trento,Italy,46.068935,11.121231,0,0,0,0,0,0,...,1746,1870,2003,2109,2220,2285,2348,2476,2602,2708
13,Piemonte,Italy,45.073274,7.680687,3,3,3,2,11,11,...,9301,9795,10353,10896,11709,12362,12924,13343,13883,14522
14,Puglia,Italy,41.125596,16.867367,0,0,0,1,3,3,...,1803,1946,2077,2182,2240,2317,2444,2514,2634,2716
15,Sardegna,Italy,39.215312,9.110616,0,0,0,0,0,0,...,722,745,794,825,874,907,922,935,975,1026
16,Sicilia,Italy,38.115697,13.362357,0,3,3,4,4,4,...,1647,1718,1791,1859,1932,1994,2046,2097,2159,2232
17,Toscana,Italy,43.769231,11.255889,0,2,2,2,8,11,...,4608,4867,5273,5499,5671,5847,6001,6173,6379,6552
18,Umbria,Italy,43.106758,12.388247,0,0,0,0,0,0,...,1078,1095,1128,1179,1210,1239,1253,1263,1289,1298
19,Valle d'Aosta,Italy,45.737503,7.320149,0,0,0,0,0,0,...,628,631,668,719,748,782,805,835,850,868
20,Veneto,Italy,45.434905,12.338452,33,43,71,111,151,191,...,9155,9625,10111,10464,10824,11226,11588,11925,12410,12933

In [55]:
datewise_df.to_csv("../data/timeseries_covid19_italy_nhu_confirmed_cases_04102020.csv", index=False)